version: '2'
services:
    flowablesimpledemoapplication-app:
        image: flowablesimpledemoapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flowablesimpledemoapplication-postgresql:5432/flowableSimpleDemoApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8558:8558
    flowablesimpledemoapplication-postgresql:
        extends:
            file: postgresql.yml
            service: flowablesimpledemoapplication-postgresql
