version: '2'
services:
    flowablesimpledemoapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/flowableSimpleDemoApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=flowableSimpleDemoApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
